language: node_js
node_js:
- 8.1
cache:
  directories:
  - node_modules
stages:
- name: deploy_master
  if: branch = master
- name: deploy_dev
  if: branch = develop
jobs:
  include:
  - stage: deploy_dev
    env:
      - REACT_APP_ENV=develop
      - AWS_DEFAULT_REGION=eu-west-1
      - secure: "iaTNGQD38RhBGmYKpwQo2vj9AQz/NkWxMJa448qwjSXwgYU55YlZ8R2W9X1tPNBxlialmiM+bqhmSGbAsGCuOJUj3LrHcCRxlfuRnOhmPeaHjetPBePRopEIezc8Y7cfAgHjsyY9uTJSglwX/bbNztKN7do3gDzZwxfHQk6RdiHwl7cMcmllkJE9MSVRIrcv7UfUdinxRq9HsB1P/ihKF2zojBiJc7Yls0oIcPj+58kfa8zGRfvmNrvgUFpLnP1pkQ7XgZ1/Zt7QTQmSzAt4Kk01tNrithQuUcRIMnsdosITY1NHtJPfOhgJxeWDW4H7s9cCetmjTPfPaY79Ei6xRhyv9XfEuM61QEeLTWan+x08rdl5rlD+aHDaxMT51JsrOHuvpgG7y32PaBY6Riz0Fk2JcGyoZ9EJesiJ+G5A3EEfseVSOnVDNPI5FtPi9Oh+lD4k7qM2qP+CneUN9kzzF5zPQvrlT8CAj2CpxCbYqwh+yhfsXxxTwYwJigAV6dH60ykcMnW1ct9t+TLSIZpgamj/V5jpkRalFQATa0nesTIsLmtC9+m4KmVUJO+3uCRTLmNPX00inwuobn3cPSoHh/2bR7NlpP0V+FGVO/OlZzISuMTFtw8rDHZE4Jdd7VLewYE4h5ymAkPWbwOHYW/RuAcAbvIoeCOwVt4q0aslT7M="
      - secure: "BF3iaxy40oh86iI4YJ07ckhigve+m+FyoWris6aIBsnZmVzOV7AfXYE+TAoXqghLQfJ3T/bFLxjbWq8wl6HB5QObg0e7zVzxzY4fzNMFyABsvdWHYhepAsZnDE3p/PPvera5spIGaqezEkiwnBljGT1CBLyHDoCF/K/16Z1ASzdLXR4P+rm7/6ezauJPnf8XTNatPSNzOlibG2Yi8vLdCdVQeBuIC8via0wnT1C7B/jxXtblYUTxvJU3fryaUHp8IxwTp4pBCdfl9Z9NNdtjp6pJ5oNJtAmDuQvci6oUJdwtDthlGr6Mgb8oLfeMUbi9PePxbIffsOkCKv3GTRgG211qPNtGpnlp7zpJvaJF+A0Qdl9ovqZLkKysgBjPV5fqzVM4xXuhAoUxIuuEsVSZKPfQypapCnN4bJHdJnod69mkx1kM9MeTbUITQFpFrziQoqyN9VP5SSM9zTdrR/zImg7J2CbVV6cIbw902uJaEhHDv8ywxY3QyD4clh0HGF8fdEOTuVCDanoAzkX6+STYoSJ1j+UHQ5q9jVnMu7UjTHIPIY+5O4+KRjsZ+DsOEhgrpkrJG5xAD1Luuu8jSMDbMJlQeCRpWnA8JKwjQvv2WmEdd91rPFijKtI49yrsZ2zbpCZJOeXE4eVO87y34eqKVqyaUzaGKo1aCU7Qi+0voww="
    script:
      - yarn global add awsmobile-cli
      - awsmobile configure aws $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_DEFAULT_REGION
      - awsmobile init fcac8ee4-f5db-4772-abc7-000b391f0864
      - awsmobile publish -c

  - stage: deploy_master
    env:
      - REACT_APP_ENV=staging
      - AWS_DEFAULT_REGION=eu-west-1
      - secure: "iaTNGQD38RhBGmYKpwQo2vj9AQz/NkWxMJa448qwjSXwgYU55YlZ8R2W9X1tPNBxlialmiM+bqhmSGbAsGCuOJUj3LrHcCRxlfuRnOhmPeaHjetPBePRopEIezc8Y7cfAgHjsyY9uTJSglwX/bbNztKN7do3gDzZwxfHQk6RdiHwl7cMcmllkJE9MSVRIrcv7UfUdinxRq9HsB1P/ihKF2zojBiJc7Yls0oIcPj+58kfa8zGRfvmNrvgUFpLnP1pkQ7XgZ1/Zt7QTQmSzAt4Kk01tNrithQuUcRIMnsdosITY1NHtJPfOhgJxeWDW4H7s9cCetmjTPfPaY79Ei6xRhyv9XfEuM61QEeLTWan+x08rdl5rlD+aHDaxMT51JsrOHuvpgG7y32PaBY6Riz0Fk2JcGyoZ9EJesiJ+G5A3EEfseVSOnVDNPI5FtPi9Oh+lD4k7qM2qP+CneUN9kzzF5zPQvrlT8CAj2CpxCbYqwh+yhfsXxxTwYwJigAV6dH60ykcMnW1ct9t+TLSIZpgamj/V5jpkRalFQATa0nesTIsLmtC9+m4KmVUJO+3uCRTLmNPX00inwuobn3cPSoHh/2bR7NlpP0V+FGVO/OlZzISuMTFtw8rDHZE4Jdd7VLewYE4h5ymAkPWbwOHYW/RuAcAbvIoeCOwVt4q0aslT7M="
      - secure: "BF3iaxy40oh86iI4YJ07ckhigve+m+FyoWris6aIBsnZmVzOV7AfXYE+TAoXqghLQfJ3T/bFLxjbWq8wl6HB5QObg0e7zVzxzY4fzNMFyABsvdWHYhepAsZnDE3p/PPvera5spIGaqezEkiwnBljGT1CBLyHDoCF/K/16Z1ASzdLXR4P+rm7/6ezauJPnf8XTNatPSNzOlibG2Yi8vLdCdVQeBuIC8via0wnT1C7B/jxXtblYUTxvJU3fryaUHp8IxwTp4pBCdfl9Z9NNdtjp6pJ5oNJtAmDuQvci6oUJdwtDthlGr6Mgb8oLfeMUbi9PePxbIffsOkCKv3GTRgG211qPNtGpnlp7zpJvaJF+A0Qdl9ovqZLkKysgBjPV5fqzVM4xXuhAoUxIuuEsVSZKPfQypapCnN4bJHdJnod69mkx1kM9MeTbUITQFpFrziQoqyN9VP5SSM9zTdrR/zImg7J2CbVV6cIbw902uJaEhHDv8ywxY3QyD4clh0HGF8fdEOTuVCDanoAzkX6+STYoSJ1j+UHQ5q9jVnMu7UjTHIPIY+5O4+KRjsZ+DsOEhgrpkrJG5xAD1Luuu8jSMDbMJlQeCRpWnA8JKwjQvv2WmEdd91rPFijKtI49yrsZ2zbpCZJOeXE4eVO87y34eqKVqyaUzaGKo1aCU7Qi+0voww="
    script:
      - yarn global add awsmobile-cli
      - awsmobile configure aws $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_DEFAULT_REGION
      - awsmobile init d5dc527a-a003-472b-a259-085080f553ac
      - awsmobile publish -c
